### ISSUE TITLE
2020-03-25 오타 및 누락

### ISSUE THREAD

**Issue by Uginim** [team-puertea/Algo#20]
### ChallengeResultVO.java
- processing_time -> processingTime
- usingMemory -> usedMemory (이건 문서가 잘못됨)

### CHALLENGE_RESULT 
- updated_at 기본값 누락
- created_at 기본값 누락

### 도전과제 결과
- USING_MEMORY -> USED_MEMORY (이거 문서가 오타 SQL에는 제대로 됨)

**Comment by yongmin-dev** [comment]
프로젝트란 이런것이구만! 화이팅 💯

**Comment by Uginim** [comment]
도전과제 결과 필드명 고침.
도전과제 결과 기본값 설정 완료.

**Comment by Uginim** [comment]
해결되었습니다.
